opcode_3={
    "18":"ADD",
    "40":"AND",
    "28":"COMP",
    "24":"DIV",
    "3C":"J",
    "30":"JEQ",
    "34":"JGT",
    "38":"JLT",
    "48":"JSUB",
    "00":"LDA",
    "50":"LDCH",
    "08":"LDL",
    "04":"LDX",
    "20":"MUL",
    "44":"OR",
    "D8":"RD",
    "4C":"RSUB",
    "0C":"STA",
    "54":"STCH",
    "14":"STL",
    "E8":"STSW",
    "10":"STX",
    "1C":"SUB",
    "E0":"TD",
    "2C":"TIX",
    "DC":"WD",
}
opCode_j={
    "3C":"J",
    "30":"JEQ",
    "34":"JGT",
    "38":"JLT",
    "48":"JSUB",
}

opcode_1={
    "C4":"FIX",
    "C0":"FLOAT",
    "F4":"HIO",
    "C8":"NORM",
    "F0":"SIO",
    "F8":"TIO"
}